spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/to_do_list_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true